name: sahopay
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # UI
  flutter_svg: ^1.1.6
  gap: ^2.0.1
  dotted_line: ^3.2.2
  google_nav_bar: ^5.0.6
  gif: ^2.2.0
  pin_code_fields: ^8.0.1

  # Animations
  flutter_bounce: ^1.1.0
  loading_animation_widget: ^1.2.0+4
  rive: ^0.11.2
  shimmer: ^3.0.0
  


  # Helpers
  flutter_screenutil: ^5.6.1
  flutter_easyloading: ^3.0.5
  location: ^5.0.2+1
  geolocator: ^10.1.0
  dropdown_search: ^3.0.1
  awesome_dialog: ^3.1.0
  flutter_dotenv: ^5.0.2
  flutter_keyboard_visibility: ^5.4.1
  url_launcher: ^6.1.10
  mask_text_input_formatter: ^2.7.0
  vibration: ^1.7.4
  local_auth: ^2.1.6
  timer_count_down: ^2.2.2
  syncfusion_flutter_sliders: ^20.3.61
  device_info_plus: ^8.0.0
  permission_handler: ^10.2.0
  platform_device_id: ^1.0.1
  flutter_local_notifications: ^16.0.0

  # State management
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  provider: ^6.0.5

   # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  #cached_network_image: ^3.2.3

  # Networking
  dio: ^5.1.1
  retrofit: ^4.0.1
  #connectivity_plus: ^3.0.3
  requests_inspector: ^2.3.5
  firebase_core: ^2.8.0
  firebase_messaging: ^14.7.4

  # Localization
  easy_localization: ^3.0.1

  # Navigation
  go_router: ^6.0.6
  local_auth_android: ^1.0.31
  local_auth_ios: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/translations/
    - assets/images/
    - assets/riv/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cabin
      fonts:
        - asset: assets/fonts/Cabin.ttf
        - asset: assets/fonts/Cabin-Italic.ttf
          weight: 700
        - asset: assets/fonts/Cabin-Italic.ttf
          weight: 800
        - asset: assets/fonts/Cabin-Italic.ttf
          weight: 900  
  
    - family: NotoSerif
      fonts:
        - asset: assets/fonts/NotoSerif.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf    
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
